### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by gesinn-it-gea** [nanasess/composer-installer-action#17]
- v2.0.2
- action used inside a docker container (https://github.com/gesinn-it/IDProvider/runs/4081854898)

```
Error: Cannot find module '@actions/core'
Require stack:
- /__w/_actions/nanasess/composer-installer-action/v2.0.2/lib/setup-composer.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/__w/_actions/nanasess/composer-installer-action/v2.0.2/lib/setup-composer.js:31:27)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
```

This is probably a side effect of removing the node_modules folder. This actions own CI does not detect this, since it explicitly calls `npm install` . Consider using https://github.com/vercel/ncc as recommended in https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github to compile your code and modules into one file used for distribution

**Comment by nanasess** [comment]
@gesinn-it
Sorry, Fixed version has been released.
https://github.com/nanasess/composer-installer-action/releases/tag/v2.0.3
